version: "3.8"

services:
  db:
    image: supabase/postgres:15.1.0.63
    container_name: supabase_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  rest:
    image: postgrest/postgrest:v10.1.2
    container_name: supabase_rest
    restart: always
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@db:5432/postgres
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMA: public,auth
      PGRST_JWT_SECRET: super-secret-jwt-token
    depends_on:
      - db

  auth:
    image: supabase/gotrue:v2.89.0
    container_name: supabase_auth
    restart: always
    ports:
      - "9999:9999"
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?search_path=auth
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: super-secret-jwt-token
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DISABLE_SIGNUP: "false"
    depends_on:
      - db

  realtime:
    image: supabase/realtime:v2.25.41
    container_name: supabase_realtime
    restart: always
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      PORT: 4000
      JWT_SECRET: super-secret-jwt-token
    depends_on:
      - db

  storage:
    image: supabase/storage-api:v0.41.3
    container_name: supabase_storage
    restart: always
    ports:
      - "5000:5000"
    environment:
      ANON_KEY: super-secret-jwt-token
      SERVICE_KEY: super-secret-jwt-token
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: super-secret-jwt-token
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - storage_data:/var/lib/storage
    depends_on:
      - db
      - rest

volumes:
  db_data:
  storage_data:
